// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

// Protobuf Java Version: 3.25.1
package com.xhf.protobuf;

public interface SubscribeRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netty.SubscribeResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 subReqID = 1;</code>
   * @return Whether the subReqID field is set.
   */
  boolean hasSubReqID();
  /**
   * <code>required int32 subReqID = 1;</code>
   * @return The subReqID.
   */
  int getSubReqID();

  /**
   * <code>required int32 respCode = 2;</code>
   * @return Whether the respCode field is set.
   */
  boolean hasRespCode();
  /**
   * <code>required int32 respCode = 2;</code>
   * @return The respCode.
   */
  int getRespCode();

  /**
   * <code>required string desc = 3;</code>
   * @return Whether the desc field is set.
   */
  boolean hasDesc();
  /**
   * <code>required string desc = 3;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>required string desc = 3;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
